from enum import Flag, auto

class CollisionTypeEnum(Flag):
    COLLISION_TYPE_LINE_OF_SIGHT = 5
    COLLISION_TYPE_CUE_BALL = 1000      # NOT USED YET
    COLLISION_TYPE_POOL_BALL = 100
    COLLISION_TYPE_POOL_TABLE_POCKET = 10
    COLLISION_TYPE_POOL_TABLE_CUSHION = 50
    COLLISION_TYPE_FLOATING_BALL = 0
    COLLISION_TYPE_GAME_TABLE = 1
    COLLISION_TYPE_FLAT_GAME_OBJECT = 501